name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          # Add commands to install dependencies and build your project
          # For example, if you are using npm:
          # npm install
          # npm run build

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: 152.42.184.243
          username: root
          key: mAhadi624234a
          source: dist
          target: /var/www/SaleNow-Frontend

# Make sure to add your SSH private key as a secret in your GitHub repository settings.
# Name the secret SSH_PRIVATE_KEY.
